version: "3.8"
services:
  qudit-core:
    build:
      context: ..
      dockerfile: docker/core.Dockerfile
    environment:
      - NODE_ID=1
    volumes:
      - ../data:/var/data
    networks: [quantum-mesh]

  metrics-collector:
    build:
      context: ..
    dockerfile: docker/metrics.Dockerfile
    ports: ["8080:8080"]   # /health and /metrics
    volumes:
      - ../metrics:/data/metrics
    networks: [quantum-mesh]

networks:
  quantum-mesh: { driver: bridge }
