name: Release Notes
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:
          script: |
            const tag = context.ref.replace('refs/tags/','');
            await github.rest.repos.generateReleaseNotes({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: tag
            });
